version: '3'
services:
  app:
    image: "${APP_IMAGE}"
    ports:
      - "9000:9000"
    restart: always
  mongoex:
    image: mongo-express
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    ports:
      - "8081:8081"
    links:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongo/data
    restart: always
