version: '3'
services:
  api:
    image: "${API_IMAGE}"
    ports:
      - "9000:9000"
    restart: always

  db:
    image: "${DB_IMAGE}"
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"