version: '3.1'
services:
  app:
    build:
      context: ./
      dockerfile: ./appDev
    ports:
      - "9000:9000"
    volumes:
      - ./app:/opt/app
    links:
      - db
    restart: always
  mongoex:
    image: mongo-express
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    ports:
      - "8081:8081"
    links:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
